"""Turn design tokens into a Remotion theme file.

Usage:  python scripts/design/generar_theme.py [tokens.json] [out.ts]
Defaults: brand/design-system/tokens.json -> channels/_template/theme.generated.ts
(for your own channel: channels/<slug>/theme.generated.ts).

Fonts are loaded with @remotion/google-fonts: the family must exist there (the script checks
node_modules and falls back to Inter with a warning). Weights are taken from the tokens.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "scripts", "design"))
from tokens_schema import load  # noqa: E402


def pascal(family):
    return re.sub(r"[^A-Za-z0-9]", "", family.title().replace(" ", ""))


def font_module(family):
    name = pascal(family)
    p = os.path.join(ROOT, "node_modules", "@remotion", "google-fonts", "dist", "cjs", name + ".js")
    return name if os.path.exists(p) else None


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "brand", "design-system", "tokens.json")
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "channels", "_template", "theme.generated.ts")
    if not os.path.exists(src):
        alt = os.path.join(ROOT, "brand", "design-system", "tokens.example.json")
        print(f"(no {src}; using the example tokens)")
        src = alt
    t = load(src)

    imports, loads, fam = [], [], {}
    for role, spec in t["font"].items():
        mod = font_module(spec["family"])
        if not mod:
            print(f"AVISO: '{spec['family']}' is not in @remotion/google-fonts; using Inter for '{role}'.")
            mod = "Inter"
        var = f"f_{role}"
        imports.append(f'import {{ loadFont as load_{role} }} from "@remotion/google-fonts/{mod}";')
        loads.append(f'const {var} = load_{role}("normal", {{ weights: ["{spec["weight"]}"], subsets: ["latin", "latin-ext"] }});')
        fam[role] = f"{var}.fontFamily"

    body = {k: t[k] for k in ("name", "color", "type", "radius", "border", "shadow", "motion", "safe", "sound", "logo")}
    weights = {r: t["font"][r]["weight"] for r in t["font"]}
    ts = "// GENERATED by scripts/design/generar_theme.py from brand/design-system/tokens.json. Do not edit by hand.\n"
    ts += "\n".join(imports) + "\n\n" + "\n".join(loads) + "\n\n"
    ts += "export const theme = {\n"
    for k, v in body.items():
        ts += f"  {k}: {json.dumps(v, ensure_ascii=False)},\n"
    ts += "  font: {\n" + "".join(f"    {r}: {fam[r]},\n" for r in fam) + "  },\n"
    ts += f"  weight: {json.dumps(weights)},\n"
    ts += "} as const;\n"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8", newline="\n").write(ts)
    print("wrote", out)


if __name__ == "__main__":
    main()
