// GENERATED by scripts/design/generar_theme.py from brand/design-system/tokens.json. Do not edit by hand.
import { loadFont as load_heading } from "@remotion/google-fonts/InterTight";
import { loadFont as load_body } from "@remotion/google-fonts/Inter";
import { loadFont as load_accent } from "@remotion/google-fonts/ShadowsIntoLightTwo";
import { loadFont as load_mono } from "@remotion/google-fonts/SpaceMono";

const f_heading = load_heading("normal", { weights: ["700"], subsets: ["latin", "latin-ext"] });
const f_body = load_body("normal", { weights: ["500"], subsets: ["latin", "latin-ext"] });
const f_accent = load_accent("normal", { weights: ["400"], subsets: ["latin", "latin-ext"] });
const f_mono = load_mono("normal", { weights: ["700"], subsets: ["latin", "latin-ext"] });

export const theme = {
  name: "Example Brand (replace me)",
  color: {"background": "#FFFFFF", "surface": "#F4F4F6", "ink": "#111111", "muted": "#6B7280", "accent": "#2F6BFF", "accent2": "#B07800", "positive": "#1E8A53", "negative": "#E5484D", "line": "#111111"},
  type: {"title": 96, "label": 48, "caption": 54, "number": 160},
  radius: {"card": 0, "pill": 999},
  border: 4,
  shadow: {"x": 9, "y": 9, "color": "#D6D6D6"},
  motion: {"enterFrames": 8, "stagger": 10, "overshoot": false},
  safe: {"vertical": {"top": 250, "bottom": 970}, "horizontal": {"top": 120, "bottom": 960}, "story": {"top": 250, "bottom": 1600}},
  sound: {"loudnessLUFS": -14, "truePeakDb": -1},
  logo: null,
  font: {
    heading: f_heading.fontFamily,
    body: f_body.fontFamily,
    accent: f_accent.fontFamily,
    mono: f_mono.fontFamily,
  },
  weight: {"heading": 700, "body": 500, "accent": 400, "mono": 700},
} as const;
